#LOGADO NO ESQUEMA FOLHA #############################################

ALTER TABLE T_FUNCIONARIO ADD SALARIO NUMBER(11,2) NOT NULL;

ALTER TABLE T_FUNCIONARIO ADD CPF NUMBER (11) NOT NULL,
CONSTRAINT UN_FUNC_CPF UNIQUE(CPF);

ALTER TABLE T_FUNCIONARIO ADD SEXO CHAR(1) NOT NULL,
CONSTRAINT CK_FUNC_SEXO CHECK (SEXO IN 'M','F');

COMMENT ON COLUMN T_FUNCIONARIO.SALARIO IS 'SALARIO DO FUNCIONARIO';
COMMENT ON COLUMN T_FUNCIONARIO.CPF IS 'CPF DO FUNCIONARIO';
COMMENT ON COLUMN T_FUNCIONARIO.SEXO IS 'SEXO DO FUNCIONARIO';


#LOGADO NO ESQUEMA VENDAS ###########################################

ALTER TABLE T_CLIENTE ADD VL_LIMITE_CRED NUMBER(11,2) NOT NULL;

ALTER TABLE T_ITEM_NF ADD CONSTRAINT CK_ITEM_NF_QTDE
CHECK (QTDE > 0);

ALTER TABLE T_CLIENTE ADD TIPO_CLI CHAR(1) NOT NULL,
CONSTRAINT CK_CLIENTE_TIPOCLI CHECK (TIPO_CLI IN 'F', 'J');

ALTER TABLE T_CLIENTE ADD CGC_CPF NUMBER(14) NOT NULL;

COMMENT ON COLUMN T_CLIENTE.VL_LIMITE_CRED IS 'VALOR DE LIMITE DE CRÉDITO';
COMMENT ON COLUMN T_CLIENTE.TIPO_CLI IS 'TIPO DE CLIENTE - FISICA OU JURIDICA';
COMMENT ON COLUMN T_CLIENTE.CGC_CPF IS 'CGC OU CPF DO CLIENTE';


#LOGADO NO ESQUEMA ESTOQUE #################################################

ALTER TABLE T_MOV_PRODUTO ADD CONSTRAINT CK_MOV_PRODUTO_TIPO 
CHECK (TIP_MOVIM IN 'E', 'S');

ALTER TABLE T_MOV_PRODUTO ADD VL_MOVIM NUMBER(11,2) NOT NULL;

COMMENT ON COLUMN T_MOV_PRODUTO.VL_MOVIM IS 'VALOR DO PRODUTO EM MOVIENTO';