CREATE DATABASE ESTOQUE;

USE ESTOQUE;

CREATE TABLE T_PRODUTO (
	COD_PRODUTO NUMBER(5) NOT NULL,
	NOM_PRODUTO VARCHAR2(30) NOT NULL,
	CD_GRUPO_PROD NUMBER(2) NOT NULL,
	CD_UNIDADE_MEDIDA VARCHAR2(3) NOT NULL,
	VL_UNITARIO NUMBER(7,2),
	SALDO_ESTOQUE NUMBER(7,2),
	QTD_ESTOQUE_MIN NUMBER(7,2),
	QTD_PTO_PEDIDO NUMBER(7,2),
	CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)

CREATE TABLE T_GRUPO_PROD (
	CD_GRUPO_PROD NUMBER(2) NOT NULL,
	DS_GRUPO_PROD VARCHAR2(30),
	CONSTRAINT PK_GRUPO_PROD PRIMARY KEY (CD_GRUPO_PROD)
);

CREATE TABLE T_UNIDADE_MEDIDA (
	CD_UNID_MEDIDA VARCHAR2(3) NOT NULL,
	DS_UNID_MEDIDA VARCHAR2(20),
	CONSTRAINT PK_UNID_MEDIDA PRIMARY KEY (CD_UNID_MEDIDA)
);

CREATE TABLE T_MOV_PRODUTO (
	COD_PRODUTO NUMBER(5) NOT NULL,
	NUM_MOVIM NUMBER(5) NOT NULL,
	DAT_MOVIM DATE,
	TIP_MOVIM CHAR(1),
	QTD_MOVIM NUMBER(3),
	MATR_FUNC_MOV NUMBER NOT NULL(5),
	CONSTRAINT PK_MOV_PRODUTO PRIMARY KEY (COD_PRODUTO, NUM_MOVIM)
);

ALTER TABLE T_PRODUTO ADD CONSTRAINT FK_PRODUTO_GRUPO 
FOREIGN KEY (CD_GRUPO_PROD) REFERENCES T_GRUPO_PROD(CD_GRUPO_PROD);

ALTER TABLE T_PRODUTO ADD CONSTRAINT FK_PRODUTO_UNID_MEDIDA 
FOREIGN KEY (CD_UNID_MEDIDA) REFERENCES T_UNIDADE_MEDIDA(CD_UNID_MEDIDA);

ALTER TABLE T_MOV_PRODUTO ADD CONSTRAINT FK_MOV_PRODUTO_PRODUTO 
FOREIGN KEY (COD_PRODUTO) REFERENCES T_PRODUTO(COD_PRODUTO);

# APÓS CRIAR ESQUEMA FOLHA 
ALTER TABLE T_MOV_PRODUTO ADD CONSTRINT FK_MOV_PRODUTO_FUNC
FOREIGN KEY (MATR_FUNC_MOV) REFERENCES FOLHA.T_FUNCIONARIO (MATRIC);

GRANT REFERENCES, SELECT ON T_PRODUTO TO VENDAS;


##################################################################


CREATE DATABASE FOLHA;

USE FOLHA;

CREATE TABLE T_FUNCIONARIO (
	MATRIC NUMBER(5) NOT NULL,
	NOME VARCHAR2(30) NOT NULL,
	DAT_ADMISS DATE,
	COD_DEPTO NUMBER,
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(MATRIC)
);

CREATE TABLE T_DEPARTAMENTO (
	COD_DEPTO NUMBER NOT NULL,
	NOM_DEPTO VARCHAR2(30) NOT NULL,
	SIGLA_DEPTO VARCHAR2(5),
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(COD_DEPTO)
);

ALTER TABLE T_FUNCIONARIO ADD CONSTRAINT FK_FUNC_DEPTO
FOREIGN KEY (COD_DEPTO) REFERENCES T_DEPARTAMENTO(COD_DEPTO);

GRANT REFERENCES, SELECT ON T_FUNCIONARIO TO ESTOQUE;

GRANT REFERENCES, SELECT ON T_FUNCIONARIO TO VENDAS;


####################################################################

CREATE DATABASE VENDAS;

USE VENDAS;

CREATE TABLE T_ITEM_NF (
	NUM_NF NUMBER(7),
	COD_PRODUTO NUMBER(5),
	QTDE NUMBER(9,2),
	VL_UNITARIO NUMBER(9,2)
	CONSTRAINT PK_ITENS_NF PRIMARY KEY(NUM_NF)
);

CREATE TABLE T_NOTA_FISCAL (
	NUM_NF NUMBER(7),
	DATA_NF DATE,
	COD_CLIENTE NUMBER(5),
	MATR_FUNC_EMI NUMBER(5),
	CONSTRAINT PK_ITENS_NF PRIMARY KEY(NUM_NF)
);

CREATE TABLE T_CLIENTE (
	COD_CLIENTE NUMBER(5),
	NOME_CLIENTE VARCHAR2(30),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(COD_CLIENTE)
);

ALTER TABLE T_NOTA_FISCAL ADD CONSTRAINT FK_NF_CLIENTE
FOREIGN KEY (COD_CLIENTE) REFERENCES T_CLIENTE(COD_CLIENTE);

ALTER TABLE T_ITEM_NF ADD CONSTRAINT FK_NF_NUMERO_NF
FOREIGN KEY (NUM_NF) REFERENCES T_NOTA_FISCAL(NUM_NF);

# APÓS CRIAR ESQUEMA FOLHA
ALTER TABLE T_NOTA_FISCAL ADD CONSTRAINT FK_NF_FUNC
FOREIGN KEY (MATR_FUNC_EMI) REFERENCES FOLHA.T_FUNCIONARIO (MATRIC);

ALTER TABLE T_ITEM_NF ADD CONSTRAINT FK_ITEM_NF_PRODUTO
FOREIGN KEY (COD_PRODUTO) REFERENCES ESTOQUE.T_PRODUTO (COD_PRODUTO);